import { BaseSeeder } from '@adonisjs/lucid/seeders'
import hash from '@adonisjs/core/services/hash'

export default class extends BaseSeeder {
  async run() {
    const password = await hash.make('123456')
    const assets = [
      // Admin Users
      {
        id: 1,
        first_name: 'John',
        last_name: 'Doe',
        address: '61 Rue de Ménilmontant',
        city: 'Paris',
        postal_code: '75020',
        country: 'France',
        phone_number: '1234567890',
        state: 'open',
        email: 'john.doe@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        first_name: 'Admin',
        last_name: 'Super',
        address: '123 Admin Street',
        city: 'Paris',
        postal_code: '75001',
        country: 'France',
        phone_number: '0123456789',
        state: 'open',
        email: 'admin@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Regular Clients
      {
        id: 3,
        first_name: 'Jane',
        last_name: 'Smith',
        address: '24 Av. Albert Petit',
        city: 'Bagneux',
        postal_code: '92220',
        country: 'France',
        phone_number: '0987654321',
        state: 'open',
        email: 'jane.smith@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        first_name: 'Alice',
        last_name: 'Johnson',
        address: '456 Client Avenue',
        city: 'Lyon',
        postal_code: '69000',
        country: 'France',
        phone_number: '0456789123',
        state: 'open',
        email: 'alice.johnson@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Delivery Personnel
      {
        id: 5,
        first_name: 'Bob',
        last_name: 'Brown',
        address: '789 Delivery Street',
        city: 'Marseille',
        postal_code: '13000',
        country: 'France',
        phone_number: '0789123456',
        state: 'open',
        email: 'bob.brown@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        first_name: 'Charlie',
        last_name: 'Wilson',
        address: '321 Fast Lane',
        city: 'Toulouse',
        postal_code: '31000',
        country: 'France',
        phone_number: '0321654987',
        state: 'open',
        email: 'charlie.wilson@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Service Providers
      {
        id: 7,
        first_name: 'Diana',
        last_name: 'Davis',
        address: '654 Service Road',
        city: 'Nice',
        postal_code: '06000',
        country: 'France',
        phone_number: '0654321789',
        state: 'open',
        email: 'diana.davis@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        first_name: 'Eva',
        last_name: 'Miller',
        address: '987 Helper Street',
        city: 'Bordeaux',
        postal_code: '33000',
        country: 'France',
        phone_number: '0987456123',
        state: 'open',
        email: 'eva.miller@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      // Merchants
      {
        id: 9,
        first_name: 'Frank',
        last_name: 'Garcia',
        address: '147 Commerce Street',
        city: 'Lille',
        postal_code: '59000',
        country: 'France',
        phone_number: '0147258369',
        state: 'open',
        email: 'frank.garcia@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        first_name: 'Grace',
        last_name: 'Martinez',
        address: '258 Shop Avenue',
        city: 'Strasbourg',
        postal_code: '67000',
        country: 'France',
        phone_number: '0258147963',
        state: 'open',
        email: 'grace.martinez@example.com',
        password: password,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]
    await this.client.table('utilisateurs').insert(assets)
  }
}
